version: "3.0"

services:
  postresql:
    image: postgres:12
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: javacamp
      POSTGRES_USER: javacamp
      POSTGRES_PASSWORD: javacamp#123
      PGDATA: /var/lib/postgresql/data/pgdata
    #    volumes:
    #      - /tmp/local/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d javacamp -U javacamp"]
      interval: 30s
      timeout: 30s
      retries: 3
